# -*- coding: utf-8 -*-
"""RGB vs HSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2koUwGOzS21VTfKk7zs0mOgNIXr3i3e
"""

import matplotlib.image as mpimg
import numpy as np
import cv2
import matplotlib.pyplot as plt

image=cv2.imread('water_balloons.jpg')
plt.imshow(image)
print(image.shape)

image_rgb=np.copy(image)
image_rgb=cv2.cvtColor(image_rgb,cv2.COLOR_BGR2RGB)
plt.imshow(image_rgb)

r=image_rgb[:,:,0]
g=image_rgb[:,:,1]
b=image_rgb[:,:,2]
f,(ax1,ax2,ax3)=plt.subplots(1,3,figsize=(24,9))
ax1.set_title('R Channel')
ax1.imshow(r,cmap='gray')
ax2.set_title('G Channel')
ax2.imshow(g,cmap='gray')
ax3.set_title('B Channel')
ax3.imshow(b,cmap='gray')

lowerpink=np.array([180,0,100])
upperpink=np.array([255,255,230])
mask_rgb=cv2.inRange(image_rgb,lowerpink,upperpink)
plt.imshow(mask_rgb)

image_rgb[mask_rgb==0]=[0,0,0]
plt.imshow(image_rgb)

image_hsv=np.copy(image)
image_hsv=cv2.cvtColor(image_hsv,cv2.COLOR_RGB2HSV)
plt.imshow(image_hsv)

h=image_hsv[:,:,0]
s=image_hsv[:,:,1]
v=image_hsv[:,:,2]
f,(ax1,ax2,ax3)=plt.subplots(1,3,figsize=(24,9))
ax1.set_title('H Channel')
ax1.imshow(h,cmap='gray')
ax2.set_title('S Channel')
ax2.imshow(s,cmap='gray')
ax3.set_title('V Channel')
ax3.imshow(v,cmap='gray')

lower_hue=np.array([140,50,50])
upper_hue=np.array([170,200,200])
mask_hsv=cv2.inRange(image_hsv,lower_hue,upper_hue)
plt.imshow(mask_hsv)

image_hsv[mask_hsv==0]=[0,0,0]
plt.imshow(image_hsv)